### ISSUE TITLE
OSV-Scanner Github Action Tracker

### ISSUE THREAD

**Issue by another-rex** [google/osv-scanner#458]
This is an issue to keep track of a list of todo's needed to complete the github action capability started in #432 

- [x] Change links that point to #432 PR branch to point to main (and/or a tagged commit of main)
- [x] Print out a link to the code scanning page as it's not clear results are shown there.
- [x] Add support for annotations
- [x] Add documentation (this is for later, as we want to dogfood it in our own repos first before broadcasting this widely)

**Comment by jess-lowe** [comment]
this should be closed when https://github.com/google/osv-scanner-action/pull/80 and https://github.com/google/osv-scanner-action/pull/79 are merged
